---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: registry.suse.com/bci/golang:1.23
    commands:
      - go install github.com/golang/mock/mockgen@v1.6.0
      - ./scripts/ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: registry.suse.com/bci/golang:1.23
    commands:
      - go install github.com/golang/mock/mockgen@v1.6.0
      - ./scripts/ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
