---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: registry.suse.com/bci/golang:1.19
    commands:
      - zypper -n install tar gzip
      - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.1;"
      - ./scripts/ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: registry.suse.com/bci/golang:1.19
    commands:
      - ./scripts/ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
