// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/lasso/pkg/client (interfaces: SharedClientFactory)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package cache -destination ./mocks_test.go github.com/rancher/lasso/pkg/client SharedClientFactory
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"

	client "github.com/rancher/lasso/pkg/client"
	gomock "go.uber.org/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockSharedClientFactory is a mock of SharedClientFactory interface.
type MockSharedClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSharedClientFactoryMockRecorder
	isgomock struct{}
}

// MockSharedClientFactoryMockRecorder is the mock recorder for MockSharedClientFactory.
type MockSharedClientFactoryMockRecorder struct {
	mock *MockSharedClientFactory
}

// NewMockSharedClientFactory creates a new mock instance.
func NewMockSharedClientFactory(ctrl *gomock.Controller) *MockSharedClientFactory {
	mock := &MockSharedClientFactory{ctrl: ctrl}
	mock.recorder = &MockSharedClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharedClientFactory) EXPECT() *MockSharedClientFactoryMockRecorder {
	return m.recorder
}

// ForKind mocks base method.
func (m *MockSharedClientFactory) ForKind(gvk schema.GroupVersionKind) (*client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForKind", gvk)
	ret0, _ := ret[0].(*client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForKind indicates an expected call of ForKind.
func (mr *MockSharedClientFactoryMockRecorder) ForKind(gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForKind", reflect.TypeOf((*MockSharedClientFactory)(nil).ForKind), gvk)
}

// ForResource mocks base method.
func (m *MockSharedClientFactory) ForResource(gvr schema.GroupVersionResource, namespaced bool) (*client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForResource", gvr, namespaced)
	ret0, _ := ret[0].(*client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForResource indicates an expected call of ForResource.
func (mr *MockSharedClientFactoryMockRecorder) ForResource(gvr, namespaced any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForResource", reflect.TypeOf((*MockSharedClientFactory)(nil).ForResource), gvr, namespaced)
}

// ForResourceKind mocks base method.
func (m *MockSharedClientFactory) ForResourceKind(gvr schema.GroupVersionResource, kind string, namespaced bool) *client.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForResourceKind", gvr, kind, namespaced)
	ret0, _ := ret[0].(*client.Client)
	return ret0
}

// ForResourceKind indicates an expected call of ForResourceKind.
func (mr *MockSharedClientFactoryMockRecorder) ForResourceKind(gvr, kind, namespaced any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForResourceKind", reflect.TypeOf((*MockSharedClientFactory)(nil).ForResourceKind), gvr, kind, namespaced)
}

// GVKForObject mocks base method.
func (m *MockSharedClientFactory) GVKForObject(obj runtime.Object) (schema.GroupVersionKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GVKForObject", obj)
	ret0, _ := ret[0].(schema.GroupVersionKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GVKForObject indicates an expected call of GVKForObject.
func (mr *MockSharedClientFactoryMockRecorder) GVKForObject(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GVKForObject", reflect.TypeOf((*MockSharedClientFactory)(nil).GVKForObject), obj)
}

// GVKForResource mocks base method.
func (m *MockSharedClientFactory) GVKForResource(gvr schema.GroupVersionResource) (schema.GroupVersionKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GVKForResource", gvr)
	ret0, _ := ret[0].(schema.GroupVersionKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GVKForResource indicates an expected call of GVKForResource.
func (mr *MockSharedClientFactoryMockRecorder) GVKForResource(gvr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GVKForResource", reflect.TypeOf((*MockSharedClientFactory)(nil).GVKForResource), gvr)
}

// IsHealthy mocks base method.
func (m *MockSharedClientFactory) IsHealthy(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockSharedClientFactoryMockRecorder) IsHealthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockSharedClientFactory)(nil).IsHealthy), ctx)
}

// IsNamespaced mocks base method.
func (m *MockSharedClientFactory) IsNamespaced(gvk schema.GroupVersionKind) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNamespaced", gvk)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsNamespaced indicates an expected call of IsNamespaced.
func (mr *MockSharedClientFactoryMockRecorder) IsNamespaced(gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNamespaced", reflect.TypeOf((*MockSharedClientFactory)(nil).IsNamespaced), gvk)
}

// NewObjects mocks base method.
func (m *MockSharedClientFactory) NewObjects(gvk schema.GroupVersionKind) (runtime.Object, runtime.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewObjects", gvk)
	ret0, _ := ret[0].(runtime.Object)
	ret1, _ := ret[1].(runtime.Object)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewObjects indicates an expected call of NewObjects.
func (mr *MockSharedClientFactoryMockRecorder) NewObjects(gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewObjects", reflect.TypeOf((*MockSharedClientFactory)(nil).NewObjects), gvk)
}

// ResourceForGVK mocks base method.
func (m *MockSharedClientFactory) ResourceForGVK(gvk schema.GroupVersionKind) (schema.GroupVersionResource, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceForGVK", gvk)
	ret0, _ := ret[0].(schema.GroupVersionResource)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResourceForGVK indicates an expected call of ResourceForGVK.
func (mr *MockSharedClientFactoryMockRecorder) ResourceForGVK(gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceForGVK", reflect.TypeOf((*MockSharedClientFactory)(nil).ResourceForGVK), gvk)
}
