name: Wrangler CI

on:
  push:
  pull_request:
    tags:
      - v*
    branches:
      - 'release/*'
      - 'main'

jobs:
  ci:
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
    runs-on: org-${{ github.repository_owner_id }}-${{ matrix.arch }}-k8s
    container: registry.suse.com/bci/golang:1.26
    steps:
    - name : Checkout repository
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name : Install mockgen
      run: go install -v -x go.uber.org/mock/mockgen@v0.6.0
    - name : Run CI
      run: bash scripts/ci
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      SETUP_GO_VERSION: '^1.26'
      GOLANG_CI_LINT_VERSION: v2.12.1
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: ${{ env.GOLANG_CI_LINT_VERSION }}

