name: CI

on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  ci:
    runs-on : ubuntu-latest
    steps:
    - name : Checkout repository
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Go
      # https://github.com/actions/setup-go/releases/tag/v5.0.0
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: Install env-test
      run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20260324065417-8c5081a9b6ba
    - name : Validate
      run: make validate
    - name : Run tests
      run: make test
    - name : Build
      run: make build
