name: golangci-lint

env:
  SETUP_GO_VERSION: '^1.24'

on:
  push:
  pull_request:
    tags:
      - v*
    branches:
      - 'release/*'
      - 'main'

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Install and run golangci-lint
        run: |
          export PATH=$PATH:/home/runner/go/bin/
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64
          golangci-lint run --verbose

# I can't get this to work with golang 1.24 and the golangci-lint-action for that version
#       - name: golangci-lint
#         uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
#         with:
#           # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
#           version: v1.64
